### ISSUE TITLE
Add full screen button and functionality to the CWRC-Writer toolbar in both reader and editing modes 

### ISSUE THREAD

**Issue by ilovan** [cwrc/Islandora-CWRC-Writer#25]
@ajmacdonald , given that the button for this functionality would be added in the CWRC-Writer toolbar, I think it may make sense for you to lead the development for this feature, with support from Echidna. Let me know if you agree.

**Comment by ajmacdonald** [comment]
@ilovan @SusanBrown Should the fullscreen mode take up the entire screen, e.g. when you fullscreen a youtube video, or should the browser's UI still be visible?

**Comment by ilovan** [comment]
I think a full screen with no browser frames is desirable because it would also help users to focus on the text they are reading/editing. 

@SusanBrown , wdyt?

**Comment by SusanBrown** [comment]
I consulted with our most active CWRC-Writer user at the moment and she thought that full Netflix mode might be a bit disorienting. 

I’m going to suggest we go with just the very top menu, and that there be an obvious button for toggling back to the standard mode. If we go this route then if the user takes their own browser into full-screen mode they have only the one bar along the top.

That is, unless Netflix mode is way easier to implement, in which case I think we can try it so long as we have the button for returning to the standard mode.

![image](https://user-images.githubusercontent.com/545952/36918597-68d3dd06-1e28-11e8-9718-5f31ee823c07.png)

**Comment by ajmacdonald** [comment]
The fully fullscreen mode is way easier to implement, and is basically done.

**Comment by SusanBrown** [comment]
OK let’s leave it at that then and see what people think. Is there a “Back to CWRC” button?

**Comment by ajmacdonald** [comment]
The button that enters fullscreen will also exit it.

**Comment by SusanBrown** [comment]
Sounds perfect. Looking forward to checking it out!

**Comment by ajmacdonald** [comment]
In order to test out CSS scoping I've pushed other changes (including this one) to dev-06. That said, the fullscreen button is not visible because of how the toolbar buttons are set for the Islandora version.

Could @jefferya or @bradklaver determine where [Drupal.settings.CWRCWriter](https://github.com/cwrc/Islandora-CWRC-Writer/blob/npmbuild/js/islandora_cwrc_writer.js#L22) is being set? This config object contains the list of buttons that should appear in the toolbar.

**Comment by bradklaver** [comment]
@ajmacdonald https://github.com/cwrc/Islandora-CWRC-Writer/blob/d07f5c42069dd5e83d71276f5963fb0a923b6396/js/islandora_cwrc_writer_note.js#L108 - is this what you're looking for? 

Drupal.settings.* is populated in a lot of places/ways

**Comment by ajmacdonald** [comment]
@bradklaver I could definitely override the config and set the buttons in JS but since the config seems to be created elsewhere outside of JS, I wanted to stick with that method in case there were reasons for doing it that way that I'm unaware of.

**Comment by bradklaver** [comment]
beta.cwrc.ca\sites\default\modules\islandora_cwrc_document\islandora_cwrc_document.module:348

@ajmacdonald I hear you.  There's no config page that lets you choose which buttons show up.  The cwrc_writer admin screen lets you change schema settings.
The only place I could change what Drupal.settings.CWRCWRiter.buttons1 said, was 
\beta.cwrc.ca\sites\default\modules\islandora_cwrc_document\islandora_cwrc_document.module:348

So ti seems the content model defines the buttons.  Since Full Screen functionality is independent of that, I wonder if you could add to the Drupal.settings.CWRCWRiter.buttons1 variable in CWRC WRiter.  Not sure though.

**Comment by ajmacdonald** [comment]
@bklaver ah so that's where it was. I will add the full screen button though JS.
Can you please make the following two changes to the buttons config in islandora_cwrc_document.module? (I don't have permission to edit that file.)
```viewsource``` should be ```viewmarkup```
```saveexitbutton``` does not seem to exist so should maybe be removed?

**Comment by ajmacdonald** [comment]
Dialogs don't currently work in fullscreen mode.

**Comment by bradklaver** [comment]
Hi @ajmacdonald I've made a branch on https://github.com/cwrc/islandora_cwrc_document.git "button-changes" 
I set dev05 and dev06 to use it

**Comment by ajmacdonald** [comment]
Still needs handling for context menus

**Comment by ilovan** [comment]
Hi @ajmacdonald . 
I can see that you are still to set up the popups, dropdowns and right-click menus. 
Do you have an idea how involved the remaining work is on these?

We plan to push the new CWRC-Writer from dev-06 to Beta by the end of this week if possible and would love to have this implemented as well  - but if you think it will take much longer than that, could you specify a commit that does not include this yet for us to reference in the submodule for beta?

Also, please don't forget that we want full screen available for both read-only and editing modes, so maybe move the full screen button from the ribbon to the main CWRC-Writer menu?

Also, if I think about it, all the things that you still need to set up are relevant to the editing mode, not the read-only one, so I think you might as well implement the button for the read-only mode now. 
Thoughts?

If you think that is a good idea, could you push the full-screen mode for the read-only view separately from the work that remains to be done for the full-screen mode for the editing environment  - so that we have at least that to add to beta if you are still aways to go complete the remaining pieces?

**Comment by ilovan** [comment]
Just tested it on dev-CWRC-Writer and it seems to have all the popups and dialogs working. Let's see how it behaves on dev-06 in the Islandora interface. 

One single observation though: can you have the full screen button 
![image](https://user-images.githubusercontent.com/6600070/38741749-e1d03bce-3ef7-11e8-9abc-32f2c1a311ca.png)

change to something similar but with the arrows pointing inwards when the application is in full screen mode, to indicate that you are going to exit the full screen mode if you press on it?

Also, as I mentioned, because the full screen mode will be available in the reader as well, can you move the button to the main menu (next to the Settings, Help and Edit Header button).

Could you push this along with the ref tag to dev-06 and prod Git-Writer today?

**Comment by ajmacdonald** [comment]
@ilovan I've updated prod. The fullscreen button in the editor mode is currently removed because I'm still trying to get certain menus working properly in fullscreen. The button is there for reader/annotator modes though.

@bklaver I tried to update dev-06 but ran into a permissions error when trying `git pull`. Could you please update it to the latest version? https://github.com/cwrc/Islandora-CWRC-Writer/commit/cd05f60a4b0f992aa7ffb84ccb5d3632f1d1ecfe

**Comment by ilovan** [comment]
this work has been completed as far as I know
